# Generated by Django 5.2.5 on 2025-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_produto_remove_venda_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_vendidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
