# Generated by Django 5.2.5 on 2025-08-15 00:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_produto_quantidade_vendidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-data_venda']},
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venda',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.produto'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='RelatorioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_itens', models.IntegerField(default=0)),
                ('numero_vendas', models.IntegerField(default=0)),
                ('resumo_produtos', models.JSONField(blank=True, default=dict)),
                ('gerado_em', models.DateTimeField(auto_now=True)),
                ('vendas_do_dia', models.ManyToManyField(related_name='relatorio_diario', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Relatório Diário',
                'verbose_name_plural': 'Relatórios Diários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_com_vendas', models.IntegerField(default=0)),
                ('relatorios_diarios', models.ManyToManyField(to='vendas.relatoriodiario')),
            ],
            options={
                'verbose_name': 'Relatório Mensal',
                'verbose_name_plural': 'Relatórios Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
